apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: default
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: satubinha-app
      restartPolicy: Never
      containers:
        - name: migrate
          image: ${ECR_REGISTRY}/satubinha-app-img-stables:migrate-${IMAGE_TAG}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: satubinha-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: satubinha-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: satubinha-secrets
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: satubinha-secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: satubinha-secrets
                  key: db_password