apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: satubinha-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/satubinha/dev/db_password"
        objectType: "ssmparameter"
        objectAlias: "db_password"
      - objectName: "/satubinha/dev/db_user"
        objectType: "ssmparameter"
        objectAlias: "db_user"
      - objectName: "/satubinha/dev/db_name"
        objectType: "ssmparameter"
        objectAlias: "db_name"
  secretObjects:
    - secretName: satubinha-secrets
      type: Opaque
      data:
        - objectName: "db_password"
          key: db_password
        - objectName: "db_user"
          key: db_user
        - objectName: "db_name"
          key: db_name