name: "[Dev] Deploy"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: satubinha-dev
  KUBECTL_VERSION: 1.27.3
  TG_VERSION: 0.67.0

jobs:
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: dev/deploy
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Setup Terragrunt
        run: |
          TG_VERSION="${{ env.TG_VERSION}}"
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then
            ARCH_TYPE="amd64"
          elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
            ARCH_TYPE="arm64"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi        
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_${ARCH_TYPE}
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/
          

      - name: Setup kubectl
        run: |
          KUBECTL_VERSION="${{ env.KUBECTL_VERSION }}"
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then
            ARCH_TYPE="amd64"
          elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
            ARCH_TYPE="arm64"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi
          curl -Lo kubectl "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${ARCH_TYPE}/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client --short

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }} --alias ${{ env.CLUSTER_NAME }}-dev
    
      - name: Verify cluster access
        run: |
          kubectl get nodes --context ${{ env.CLUSTER_NAME }}-dev

      - name: Apply service account
        run: |
            APP_ROLE_ARN=$(cd environments/dev/app-infra && terragrunt output -raw app_role_arn)
            envsubst < k8s/dev/serviceaccount.yaml | kubectl apply -f - \
            --context ${{ env.CLUSTER_NAME }}-dev

      - name: Run migrations
        run: |
            kubectl apply -f k8s/dev/job-migrate.yaml --context ${{ env.CLUSTER_NAME }}-dev

      - name: Wait for migrations
        run: |
            kubectl wait --for=condition=complete job/migrate \
            --timeout=120s \
            --context ${{ env.CLUSTER_NAME }}-dev

      - name: Deploy application
        run: |
            kubectl apply -f k8s/dev/deployment-api.yaml --context ${{ env.CLUSTER_NAME }}-dev
            kubectl apply -f k8s/dev/deployment-front.yaml --context ${{ env.CLUSTER_NAME }}-dev
            kubectl apply -f k8s/dev/service.yaml --context ${{ env.CLUSTER_NAME }}-dev
            kubectl apply -f k8s/dev/ingress.yaml --context ${{ env.CLUSTER_NAME }}-dev   